pipeline:
    name: build01
    identifier: build01
    projectIdentifier: proj03
    orgIdentifier: org3
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: git001
                repoName: firstdrone1
                build: <+input>
    stages:
        - stage:
              name: approve001
              identifier: approve001
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: approval001
                                identifier: approval001
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups:
                                            - account.approver
                                            - account.devops
                                    approverInputs: []
              tags: {}
        - stage:
              name: build
              identifier: build
              description: ""
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesHosted
                      spec:
                          identifier: k8s-hosted-infra
                  execution:
                      steps:
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: doc
                                identifier: doc
                                spec:
                                    connectorRef: doc001
                                    repo: abyalias/doc
                                    tags:
                                        - tags001
